name: news
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # hexcolor: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^7.0.0
  conditional_builder: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.6
  webview_flutter: ^2.0.8
  responsive_sizer: ^3.1.1
  scroll_page_view: ^1.0.2
  carousel_slider: ^4.0.0
  transparent_image: ^2.0.0
  localize_and_translate: ^4.1.1
  intl: ^0.17.0
  timeago: ^3.3.0
  sqflite: ^2.0.0
  url_launcher: ^6.0.20
  share: ^2.0.4
  flutter_switch: ^0.3.2
  package_info_plus: ^3.0.2
  flutter_launcher_icons: ^0.10.0
  animated_splash_screen: ^1.3.0

flutter_icons:
  android: true
  image_path: "assets/image/logo.jpg"
  
  

  





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/Rectangle 15.png
    - assets/image/facebook.png
    - assets/image/gmail.png
    - assets/image/nodata.png
    - assets/image/linkedin.png
    - assets/image/us_flag.png
    - assets/image/eg_flag.png
    - assets/image/bad_request_error.png
    - assets/image/fetch_data_error.png
    - assets/image/socket_error.png
    - assets/image/unauthorised_error.png
    - assets/image/logo.jpg
    - assets/image/loading.png
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/image/emty.png

    

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ananda
      fonts:
        - asset: assets/font/font.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
